apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: jenkins
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
                - alertmanager.jenkins.svc.cluster.local:9093

    scrape_configs:
      - job_name: "flask-app"
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - jenkins
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: flask-app
          - source_labels: [__meta_kubernetes_service_port_name]
            action: keep
            regex: http
